# Generated by Django 3.2 on 2021-04-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vazifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mavzu', models.CharField(max_length=200)),
                ('tugadi', models.BooleanField(default=False)),
                ('yaratish', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
